# --- !Ups

create table LOGIN_IDENTITY (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER_ID VARCHAR(254) NOT NULL,
  PROVIDER_ID VARCHAR(254) NOT NULL,
  FIRST_NAME VARCHAR(254) NOT NULL,
  LAST_NAME VARCHAR(254) NOT NULL,
  FULL_NAME VARCHAR(254) NOT NULL,
  EMAIL VARCHAR(254),
  AVATAR_URL VARCHAR(254),
  AUTH_METHOD VARCHAR(254) NOT NULL,
  TOKEN VARCHAR(254),
  SECRET VARCHAR(254),
  ACCESS_TOKEN VARCHAR(254),
  TOKEN_TYPE VARCHAR(254),
  EXPIRES_IN INTEGER,
  REFRESH_TOKEN VARCHAR(254));

# --- !Downs

drop table LOGIN_IDENTITY;