# --- !Ups
ALTER TABLE USER_ACCOUNT ADD COLUMN ADMIN TINYINT(1) DEFAULT 0
AFTER FACILITATOR;
ALTER TABLE USER_ACCOUNT ADD COLUMN MEMBER TINYINT(1) DEFAULT 0
AFTER ADMIN;
ALTER TABLE USER_ACCOUNT ADD COLUMN REGISTERED TINYINT(1) DEFAULT 0
AFTER MEMBER;

UPDATE USER_ACCOUNT
SET REGISTERED = 1
WHERE COORDINATOR = 1;
UPDATE USER_ACCOUNT
SET REGISTERED = 1
WHERE FACILITATOR = 1;
UPDATE USER_ACCOUNT a, MEMBER m
SET a.MEMBER = 1, a.REGISTERED = 1
WHERE a.PERSON_ID = m.OBJECT_ID AND m.PERSON = 1;
ALTER TABLE USER_ACCOUNT DROP COLUMN ROLE;

# --- !Downs
ALTER TABLE USER_ACCOUNT DROP COLUMN ADMIN;
ALTER TABLE USER_ACCOUNT DROP COLUMN MEMBER;
ALTER TABLE USER_ACCOUNT DROP COLUMN REGISTERED;
