# --- !Ups
ALTER TABLE USER_ACCOUNT ADD COLUMN BY_EMAIL TINYINT(1) DEFAULT 0 AFTER PERSON_ID;
CREATE TABLE IF NOT EXISTS PASSWORD_IDENTITY(
  USER_ID BIGINT,
  EMAIL VARCHAR(254) NOT NULL,
  PASSWORD VARCHAR(254) NOT NULL,
  FIRST_NAME VARCHAR(254),
  LAST_NAME VARCHAR(254),
  HASHER VARCHAR(254) NOT NULL
);
RENAME TABLE `LOGIN_IDENTITY` TO `SOCIAL_IDENTITY`;
CREATE TABLE IF NOT EXISTS `PASSWORD_TOKEN`(
  USER_ID VARCHAR(254) NOT NULL PRIMARY KEY,
  EMAIL VARCHAR(254) NOT NULL,
  CREATED DATETIME NOT NULL,
  EXPIRE DATETIME NOT NULL,
  SIGN_UP TINYINT(1) NOT NULL DEFAULT 0
);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN PROFILE_URL VARCHAR(254);
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = TWITTER_HANDLE WHERE PROVIDER_ID = 'twitter';
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = LINKEDIN_URL WHERE PROVIDER_ID = 'linkedin';
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = FACEBOOK_URL WHERE PROVIDER_ID = 'facebook';
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = GOOGLE_PLUS_URL WHERE PROVIDER_ID = 'google';
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN TWITTER_HANDLE;
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN LINKEDIN_URL;
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN FACEBOOK_URL;
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN GOOGLE_PLUS_URL;

CREATE TABLE IF NOT EXISTS `REGISTERING_USER`(
  USER_ID VARCHAR(254) NOT NULL,
  PROVIDER_ID VARCHAR(254) NOT NULL,
  PRIMARY KEY IDENTIFIER (USER_ID, PROVIDER_ID)
);
CREATE TABLE IF NOT EXISTS `EMAIL_TOKEN`(
  TOKEN VARCHAR(254) NOT NULL PRIMARY KEY,
  EMAIL VARCHAR(254) NOT NULL,
  USER_ID BIGINT NOT NULL,
  CREATED DATETIME NOT NULL,
  EXPIRE DATETIME NOT NULL
);
ALTER TABLE `PERSON` ADD COLUMN EMAIL VARCHAR(254) NOT NULL AFTER LAST_NAME;
UPDATE `PERSON`, `SOCIAL_PROFILE` SET `PERSON`.EMAIL = `SOCIAL_PROFILE`.EMAIL WHERE `SOCIAL_PROFILE`.OBJECT_ID = `PERSON`.ID AND `SOCIAL_PROFILE`.OBJECT_TYPE = 0;
ALTER TABLE `BRAND` ADD COLUMN CONTACT_EMAIL VARCHAR(254) NOT NULL AFTER BLOG;
UPDATE `BRAND`, `SOCIAL_PROFILE` SET CONTACT_EMAIL = `SOCIAL_PROFILE`.EMAIL WHERE `SOCIAL_PROFILE`.OBJECT_ID = `BRAND`.ID AND `SOCIAL_PROFILE`.OBJECT_TYPE = 1 AND `SOCIAL_PROFILE`.EMAIL IS NOT NULL;
ALTER TABLE `ORGANISATION` ADD COLUMN CONTACT_EMAIL VARCHAR(254) AFTER BLOG;
UPDATE `ORGANISATION`, `SOCIAL_PROFILE` SET CONTACT_EMAIL = `SOCIAL_PROFILE`.EMAIL WHERE `SOCIAL_PROFILE`.OBJECT_ID = `ORGANISATION`.ID AND `SOCIAL_PROFILE`.OBJECT_TYPE = 2 AND `SOCIAL_PROFILE`.EMAIL IS NOT NULL;
ALTER TABLE `SOCIAL_PROFILE` DROP COLUMN EMAIL;
# --- !Downs
ALTER TABLE `SOCIAL_PROFILE` ADD COLUMN EMAIL VARCHAR(254);
UPDATE `SOCIAL_PROFILE`, `ORGANISATION` SET EMAIL = `ORGANISATION`.CONTACT_EMAIL WHERE `SOCIAL_PROFILE`.OBJECT_ID = `ORGANISATION`.ID AND `SOCIAL_PROFILE`.OBJECT_TYPE = 2 AND `ORGANISATION`.CONTACT_EMAIL IS NOT NULL
ALTER TABLE `ORGANISATION` DROP COLUMN CONTACT_EMAIL;
UPDATE `SOCIAL_PROFILE`, `BRAND` SET EMAIL = `BRAND`.CONTACT_EMAIL WHERE `SOCIAL_PROFILE`.OBJECT_ID = `BRAND`.ID AND `SOCIAL_PROFILE`.OBJECT_TYPE = 1 AND `BRAND`.CONTACT_EMAIL IS NOT NULL
ALTER TABLE `BRAND` DROP COLUMN CONTACT_EMAIL;
UPDATE `SOCIAL_PROFILE`, `PERSON` SET `SOCIAL_PROFILE`.EMAIL = `PERSON`.EMAIL WHERE `SOCIAL_PROFILE`.OBJECT_ID = `PERSON`.ID AND `SOCIAL_PROFILE`.OBJECT_TYPE = 0;
ALTER TABLE `PERSON` DROP COLUMN EMAIL;

DROP TABLE IF EXISTS `EMAIL_MAIL_TOKEN`;
DROP TABLE IF EXISTS `REGISTERING_USER`;
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN GOOGLE_PLUS_URL VARCHAR(254);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN FACEBOOK_URL VARCHAR(254);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN LINKEDIN_URL VARCHAR(254);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN TWITTER_HANDLE VARCHAR(254);
UPDATE `SOCIAL_IDENTITY` SET TWITTER_HANDLE = PROFILE_URL WHERE PROVIDER_ID = 'twitter';
UPDATE `SOCIAL_IDENTITY` SET FACEBOOK_URL = PROFILE_URL WHERE PROVIDER_ID = 'facebook';
UPDATE `SOCIAL_IDENTITY` SET LINKEDIN_URL = PROFILE_URL WHERE PROVIDER_ID = 'linkedin';
UPDATE `SOCIAL_IDENTITY` SET GOOGLE_PLUS_URL = PROFILE_URL WHERE PROVIDER_ID = 'google';
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN PROFILE_URL;

DROP TABLE IF EXISTS `PASSWORD_TOKEN`;
RENAME TABLE `SOCIAL_IDENTITY` TO `LOGIN_IDENTITY`;
DROP TABLE PASSWORD_IDENTITY;
ALTER TABLE USER_ACCOUNT DROP COLUMN BY_EMAIL;
