# --- !Ups
ALTER TABLE USER_ACCOUNT ADD COLUMN EMAIL VARCHAR(254) AFTER PERSON_ID;
CREATE TABLE IF NOT EXISTS PASSWORD_IDENTITY(
  USER_ID BIGINT,
  EMAIL VARCHAR(254) NOT NULL,
  PASSWORD VARCHAR(254) NOT NULL,
  FIRST_NAME VARCHAR(254),
  LAST_NAME VARCHAR(254),
  HASHER VARCHAR(254) NOT NULL
);
RENAME TABLE `LOGIN_IDENTITY` TO `SOCIAL_IDENTITY`;
CREATE TABLE IF NOT EXISTS `MAIL_TOKEN`(
  USER_ID VARCHAR(254) NOT NULL PRIMARY KEY,
  EMAIL VARCHAR(254) NOT NULL,
  CREATED DATETIME NOT NULL,
  EXPIRE DATETIME NOT NULL,
  SIGN_UP TINYINT(1) NOT NULL DEFAULT 0
);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN PROFILE_URL VARCHAR(254);
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = TWITTER_HANDLE WHERE PROVIDER_ID = 'twitter';
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = LINKEDIN_URL WHERE PROVIDER_ID = 'linkedin';
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = FACEBOOK_URL WHERE PROVIDER_ID = 'facebook';
UPDATE `SOCIAL_IDENTITY` SET PROFILE_URL = GOOGLE_PLUS_URL WHERE PROVIDER_ID = 'google';
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN TWITTER_HANDLE;
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN LINKEDIN_URL;
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN FACEBOOK_URL;
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN GOOGLE_PLUS_URL;

# --- !Downs
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN GOOGLE_PLUS_URL VARCHAR(254);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN FACEBOOK_URL VARCHAR(254);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN LINKEDIN_URL VARCHAR(254);
ALTER TABLE `SOCIAL_IDENTITY` ADD COLUMN TWITTER_HANDLE VARCHAR(254);
UPDATE `SOCIAL_IDENTITY` SET TWITTER_HANDLE = PROFILE_URL WHERE PROVIDER_ID = 'twitter';
UPDATE `SOCIAL_IDENTITY` SET FACEBOOK_URL = PROFILE_URL WHERE PROVIDER_ID = 'facebook';
UPDATE `SOCIAL_IDENTITY` SET LINKEDIN_URL = PROFILE_URL WHERE PROVIDER_ID = 'linkedin';
UPDATE `SOCIAL_IDENTITY` SET GOOGLE_PLUS_URL = PROFILE_URL WHERE PROVIDER_ID = 'google';
ALTER TABLE `SOCIAL_IDENTITY` DROP COLUMN PROFILE_URL;

DROP TABLE IF EXISTS `MAIL_TOKEN`;
RENAME TABLE `SOCIAL_IDENTITY` TO `LOGIN_IDENTITY`;
DROP TABLE PASSWORD_IDENTITY;
ALTER TABLE USER_ACCOUNT DROP COLUMN EMAIL;
