# --- !Ups
ALTER TABLE USER_ACCOUNT ADD COLUMN EMAIL VARCHAR(254)
AFTER PERSON_ID;
ALTER TABLE USER_ACCOUNT ADD COLUMN PASSWORD VARCHAR(254)
AFTER EMAIL;
ALTER TABLE USER_ACCOUNT ADD CONSTRAINT UNIQUE (EMAIL);

# --- !Downs
ALTER TABLE USER_ACCOUNT DROP COLUMN EMAIL;
ALTER TABLE USER_ACCOUNT DROP COLUMN PASSWORD;
