# --- !Ups
CREATE TABLE BRAND_SETTINGS(
  BRAND_ID BIGINT NOT NULL PRIMARY KEY,
  CERTIFICATES TINYINT(1) NOT NULL DEFAULT 0,
  LICENSE_EXPIRATION_EMAIL TINYINT(1) NOT NULL DEFAULT 0,
  LICENSE_EXPIRATION_EMAIL_BODY TEXT,
  CONSTRAINT BRAND_SETTINGS_FK FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID) ON DELETE CASCADE ON UPDATE NO ACTION
);
INSERT INTO BRAND_SETTINGS (BRAND_ID, CERTIFICATES) SELECT ID, GENERATE_CERT FROM BRAND;
ALTER TABLE BRAND DROP COLUMN GENERATE_CERT;

# --- !Downs
ALTER TABLE BRAND ADD COLUMN GENERATE_CERT TINYINT(1) NOT NULL DEFAULT 0 AFTER PICTURE;
UPDATE BRAND, BRAND_SETTINGS SET GENERATE_CERT = CERTIFICATES WHERE BRAND.ID = BRAND_SETTINGS.BRAND_ID;
DROP TABLE BRAND_SETTINGS;
