# --- !Ups
CREATE TABLE BRAND_BADGE(
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID BIGINT NOT NULL,
  NAME VARCHAR(254) NOT NULL,
  FILE VARCHAR(254) NOT NULL,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(254) NOT NULL,
  UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR(254) NOT NULL,
  CONSTRAINT BRAND_BADGE_FK FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID) ON DELETE CASCADE ON UPDATE NO ACTION
);
ALTER TABLE FACILITATOR ADD COLUMN BADGES VARCHAR(254);

# --- !Downs
ALTER TABLE FACILITATOR DROP COLUMN BADGES;
DROP TABLE BRAND_BADGE;