# --- !Ups
create table EVENT_ATTENDEE (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EVENT_ID BIGINT NOT NULL,
  PERSON_ID BIGINT,
  FIRST_NAME VARCHAR(254) NOT NULL,
  LAST_NAME VARCHAR(254) NOT NULL,
  EMAIL VARCHAR(254) NOT NULL,
  DATE_OF_BIRTH DATE DEFAULT NULL,
  COUNTRY_CODE CHAR(2),
  CITY VARCHAR(254),
  STREET_1 VARCHAR(254),
  STREET_2 VARCHAR(254),
  PROVINCE VARCHAR(254),
  POSTCODE VARCHAR(254),
  EVALUATION_ID BIGINT,
  CERTIFICATE VARCHAR(254),
  ISSUED DATE,
  ORGANISATION VARCHAR(254),
  COMMENT VARCHAR(254),
  ROLE VARCHAR(254)
);

alter table EVENT_ATTENDEE add constraint ATTENDEE_FK foreign key(EVENT_ID) references EVENT(ID) on update NO ACTION on delete CASCADE;

# --- !Downs
alter table EVENT_ATTENDEE drop foreign key ATTENDEE_FK;
drop table EVENT_ATTENDEE;
