# --- !Ups
ALTER TABLE EVENT_REQUEST ADD COLUMN HASHED_ID CHAR(64) NOT NULL DEFAULT "" AFTER EMAIL;
ALTER TABLE EVENT_REQUEST ADD COLUMN UNSUBSCRIBED TINYINT(1) NOT NULL DEFAULT 0 AFTER HASHED_ID;
UPDATE EVENT_REQUEST SET HASHED_ID = MD5(EMAIL);

# --- !Downs
ALTER TABLE EVENT_REQUEST DROP COLUMN HASHED_ID;
ALTER TABLE EVENT_REQUEST DROP COLUMN UNSUBSCRIBED;