# --- !Ups
ALTER TABLE EVENT ADD COLUMN HASHED_ID CHAR(64) NOT NULL AFTER RATING;
ALTER TABLE EVENT ADD COLUMN PUBLIC_PAGE TINYINT(1) NOT NULL DEFAULT 0 AFTER HASHED_ID;
UPDATE EVENT SET HASHED_ID = MD5(ID);

# --- !Downs
ALTER TABLE EVENT DROP COLUMN HASHED_ID;
ALTER TABLE EVENT DROP COLUMN PUBLIC_PAGE;