# --- !Ups
UPDATE USER_ACCOUNT u, SOCIAL_IDENTITY s SET u.FACEBOOK_URL = s.USER_ID WHERE s.PROFILE_URL = u.FACEBOOK_URL AND s.PROVIDER_ID = "facebook";
UPDATE USER_ACCOUNT u, SOCIAL_IDENTITY s SET u.LINKEDIN_URL = s.USER_ID WHERE s.PROFILE_URL = u.LINKEDIN_URL AND s.PROVIDER_ID = "linkedin";
UPDATE USER_ACCOUNT u, SOCIAL_IDENTITY s SET u.GOOGLE_PLUS_URL = s.USER_ID WHERE s.PROFILE_URL = u.GOOGLE_PLUS_URL AND s.PROVIDER_ID = "google";
UPDATE USER_ACCOUNT u, SOCIAL_IDENTITY s SET u.TWITTER_HANDLE = s.USER_ID WHERE s.PROFILE_URL = u.TWITTER_HANDLE AND s.PROVIDER_ID = "twitter";
UPDATE USER_ACCOUNT SET LINKEDIN_URL = NULL WHERE LINKEDIN_URL LIKE "%linkedin%";
UPDATE USER_ACCOUNT SET GOOGLE_PLUS_URL = NULL WHERE GOOGLE_PLUS_URL LIKE "%google%";
UPDATE USER_ACCOUNT SET FACEBOOK_URL = NULL WHERE FACEBOOK_URL LIKE "%facebook%";
UPDATE USER_ACCOUNT SET TWITTER_HANDLE = NULL WHERE TWITTER_HANDLE REGEXP "[a-z]+";

DROP INDEX IDX_FACEBOOK_URL ON USER_ACCOUNT;
DROP INDEX IDX_LINKEDIN_URL ON USER_ACCOUNT;
DROP INDEX IDX_GOOGLE_PLUS_URL ON USER_ACCOUNT;
DROP INDEX IDX_TWITTER_HANDLE ON USER_ACCOUNT;

ALTER TABLE USER_ACCOUNT CHANGE TWITTER_HANDLE TWITTER VARCHAR(254);
ALTER TABLE USER_ACCOUNT CHANGE LINKEDIN_URL LINKEDIN VARCHAR(254);
ALTER TABLE USER_ACCOUNT CHANGE GOOGLE_PLUS_URL GOOGLE VARCHAR(254);
ALTER TABLE USER_ACCOUNT CHANGE FACEBOOK_URL FACEBOOK VARCHAR(254);

CREATE UNIQUE INDEX IDX_FACEBOOK on USER_ACCOUNT (FACEBOOK);
CREATE UNIQUE INDEX IDX_LINKEDIN on USER_ACCOUNT (LINKEDIN);
CREATE UNIQUE INDEX IDX_GOOGLE on USER_ACCOUNT (GOOGLE);
CREATE UNIQUE INDEX IDX_TWITTER on USER_ACCOUNT (TWITTER);

ALTER TABLE SOCIAL_IDENTITY DROP COLUMN PROFILE_URL;