# --- !Ups
ALTER TABLE PERSON ADD COLUMN HASHED_ID CHAR(64) NOT NULL AFTER ID;
UPDATE PERSON SET HASHED_ID = MD5(ID);
CREATE UNIQUE INDEX IDX_HASHED_ID on PERSON (HASHED_ID);
ALTER TABLE BRAND ADD COLUMN HASHED_ID CHAR(8) NOT NULL AFTER ACTIVE;
ALTER TABLE BRAND ADD COLUMN TMP_HASHED_ID CHAR(64) NOT NULL AFTER HASHED_ID;
UPDATE BRAND SET TMP_HASHED_ID = MD5(ID);
UPDATE BRAND SET HASHED_ID = SUBSTR(TMP_HASHED_ID, 1, 8);
ALTER TABLE BRAND DROP COLUMN TMP_HASHED_ID;
CREATE UNIQUE INDEX IDX_HASHED_ID on BRAND (HASHED_ID);

# --- !Downs
DROP INDEX IDX_HASHED_ID ON BRAND;
ALTER TABLE BRAND DROP COLUMN HASHED_ID;
DROP INDEX IDX_HASHED_ID ON PERSON;
ALTER TABLE PERSON DROP COLUMN HASHED_ID;
