# --- !Ups
CREATE TABLE NOTIFICATION(
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PERSON_ID` BIGINT NOT NULL,
  `BODY` MEDIUMTEXT NOT NULL,
  `TYPE` VARCHAR(20) NOT NULL,
  `UNREAD` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

# --- !Downs
DROP TABLE NOTIFICATION;
