# --- !Ups
CREATE TABLE PEER_CREDIT(
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `BRAND_ID` BIGINT NOT NULL,
  `RECEIVER_ID` BIGINT NOT NULL,
  `GIVER_ID` BIGINT NOT NULL,
  `AMOUNT` INT NOT NULL,
  `REASON` VARCHAR(254) NOT NULL,
  `CREATED` DATETIME NOT NULL);

CREATE TABLE CREDIT_LIMIT(
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `BRAND_ID` BIGINT NOT NULL,
  `AMOUNT` INT NOT NULL,
  `MONTH` DATETIME NOT NULL);

# --- !Downs
DROP TABLE PEER_CREDIT;
DROP TABLE CREDIT_LIMIT;