# --- !Ups
CREATE TABLE COMMECIAL_CUSTOMER(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(254) NOT NULL,
  EMAIL VARCHAR(254) NOT NULL,
  INTERESTED TINYINT(1) NOT NULL
);

# --- !Downs
DROP TABLE COMMECIAL_CUSTOMER;
