# --- !Ups
ALTER TABLE ORGANISATION ADD COLUMN LOGO_ID CHAR(32) AFTER LOGO;
UPDATE ORGANISATION SET LOGO_ID = ID WHERE LOGO = 1;
ALTER TABLE ORGANISATION DROP COLUMN LOGO;
ALTER TABLE PERSON ADD COLUMN SIGNATURE_ID CHAR(32) AFTER SIGNATURE;
UPDATE PERSON SET SIGNATURE_ID = ID WHERE SIGNATURE = 1;
ALTER TABLE PERSON DROP COLUMN SIGNATURE;
ALTER TABLE PERSON ADD COLUMN PHOTO_ID CHAR(32) AFTER PHOTO;
UPDATE PERSON SET PHOTO_ID = ID WHERE PHOTO like '%cloudfront%';

# --- !Downs
ALTER TABLE PERSON DROP COLUMN PHOTO_ID;

ALTER TABLE PERSON ADD COLUMN SIGNATURE TINYINT(1) NOT NULL DEFAULT 0 AFTER PHOTO;
UPDATE PERSON SET SIGNATURE = 1 WHERE SIGNATURE_ID IS NOT NULL;
ALTER TABLE PERSON DROP COLUMN SIGNATURE_ID;


ALTER TABLE ORGANISATION ADD COLUMN LOGO TINYINT(1) NOT NULL DEFAULT 0 AFTER ABOUT;
UPDATE ORGANISATION SET LOGO = 1 WHERE LOGO_ID IS NOT NULL;
ALTER TABLE ORGANISATION DROP COLUMN LOGO_ID;
