# --- !Ups
ALTER TABLE SOCIAL_IDENTITY ADD COLUMN EXTRA_INFO VARCHAR(254);
ALTER TABLE USER_ACCOUNT ADD COLUMN MAILCHIMP VARCHAR(254) AFTER GOOGLE;
CREATE UNIQUE INDEX IDX_MAILCHIMP on USER_ACCOUNT (MAILCHIMP);

# --- !Downs
DROP INDEX IDX_MAILCHIMP ON USER_ACCOUNT;
ALTER TABLE USER_ACCOUNT DROP COLUMN MAILCHIMP;
ALTER TABLE SOCIAL_IDENTITY DROP COLUMN EXTRA_INFO;