# --- !Ups
ALTER TABLE SOCIAL_IDENTITY ADD COLUMN EXTRA_INFO VARCHAR(254);
ALTER TABLE USER_ACCOUNT ADD COLUMN MAILCHIMP VARCHAR(254) AFTER GOOGLE;
CREATE UNIQUE INDEX IDX_MAILCHIMP on USER_ACCOUNT (MAILCHIMP);

CREATE TABLE MAILCHIMP_LIST(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  LIST_NAME VARCHAR(254) NOT NULL,
  LIST_ID CHAR(32) NOT NULL,
  BRAND_ID BIGINT NOT NULL,
  PERSON_ID BIGINT NOT NULL,
  ALL_ATTENDEES TINYINT(1) NOT NULL DEFAULT 1
);
ALTER TABLE MAILCHIMP_LIST ADD CONSTRAINT MAILCHIMP_LIST_BRAND_FK FOREIGN KEY(BRAND_ID) REFERENCES BRAND(ID)
  ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE MAILCHIMP_LIST ADD CONSTRAINT MAILCHIMP_LIST_PERSON_FK FOREIGN KEY(PERSON_ID) REFERENCES PERSON(ID)
  ON UPDATE NO ACTION ON DELETE CASCADE;

# --- !Downs
ALTER TABLE MAILCHIMP_LIST DROP FOREIGN KEY MAILCHIMP_LIST_BRAND_FK;
ALTER TABLE MAILCHIMP_LIST DROP FOREIGN KEY MAILCHIMP_LIST_PERSON_FK;
DROP TABLE MAILCHIMP_LIST;

DROP INDEX IDX_MAILCHIMP ON USER_ACCOUNT;
ALTER TABLE USER_ACCOUNT DROP COLUMN MAILCHIMP;
ALTER TABLE SOCIAL_IDENTITY DROP COLUMN EXTRA_INFO;