# --- !Ups
CREATE TABLE TRIAL_COUPON (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(25) NOT NULL UNIQUE,
  OWNER VARCHAR(254) NOT NULL,
  EMAIL VARCHAR(254) NOT NULL
) CHARACTER SET utf8;

# --- !Downs
DROP TABLE TRIAL_COUPON;