# --- !Ups

alter table `BRAND` change `CREATED` `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
alter table `ACTIVITY` change `CREATED` `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

# --- !Downs
