# --- !Ups

create table PRODUCT (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(254) NOT NULL UNIQUE,
  SUBTITLE VARCHAR(254),
  URL VARCHAR(1024),
  CATEGORY VARCHAR(254),
  PARENT_ID BIGINT,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(254) NOT NULL DEFAULT 'Sergey Kotlov',
  UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR(254) NOT NULL DEFAULT 'Sergey Kotlov'
);


-- alter table PRODUCT add constraint PARENT_FK foreign key(PARENT_ID) references PRODUCT(ID) on update NO ACTION on delete NO ACTION;

create table PRODUCT_BRAND_RELATIONS (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT NOT NULL,
  BRAND_ID BIGINT NOT NULL);

alter table PRODUCT_BRAND_RELATIONS add constraint BRAND_PRODUCT_FK foreign key(PRODUCT_ID) references PRODUCT(ID) on update NO ACTION on delete NO ACTION;

alter table PRODUCT_BRAND_RELATIONS add constraint PRODUCT_BRAND_FK foreign key(BRAND_ID) references BRAND(ID) on update NO ACTION on delete NO ACTION;

# --- !Downs

drop table PRODUCT;
drop table PRODUCT_BRAND_RELATIONS;

