# --- !Ups

create table CONTRIBUTIONS (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CONTRIBUTOR_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  IS_PERSON TINYINT NOT NULL DEFAULT 1,
  ROLE VARCHAR(254) NOT NULL
);

alter table CONTRIBUTIONS add constraint CONTRIBUTION_FK foreign key(PRODUCT_ID) references PRODUCT(ID) on update NO ACTION on delete NO ACTION;

# --- !Downs

drop table CONTRIBUTIONS;

