# --- !Ups

rename table PRODUCT_BRAND_RELATIONS to PRODUCT_BRAND_ASSOCIATION;
rename table CONTRIBUTIONS to CONTRIBUTION;
# --- !Downs

rename table PRODUCT_BRAND_ASSOCIATION to PRODUCT_BRAND_RELATIONS;
rename table CONTRIBUTION to CONTRIBUTIONS;
