# --- !Ups

create table if not exists SOCIAL_PROFILE (
  PERSON_ID BIGINT NOT NULL PRIMARY KEY,
  TWITTER_HANDLE VARCHAR(254),
  FACEBOOK_URL VARCHAR(254),
  LINKEDIN_URL VARCHAR(254),
  GOOGLE_PLUS_URL VARCHAR(254));

insert into SOCIAL_PROFILE (PERSON_ID, TWITTER_HANDLE, FACEBOOK_URL, LINKEDIN_URL, GOOGLE_PLUS_URL)
  select ID, TWITTER_HANDLE, FACEBOOK_URL, LINKEDIN_URL, GOOGLE_PLUS_URL from PERSON;

alter table PERSON drop column TWITTER_HANDLE;
alter table PERSON drop column FACEBOOK_URL;
alter table PERSON drop column LINKEDIN_URL;
alter table PERSON drop column GOOGLE_PLUS_URL;

# --- !Downs
alter table PERSON add column TWITTER_HANDLE VARCHAR(254);
alter table PERSON add column FACEBOOK_URL VARCHAR(254);
alter table PERSON add column LINKEDIN_URL VARCHAR(254);
alter table PERSON add column GOOGLE_PLUS_URL VARCHAR(254);

update PERSON, SOCIAL_PROFILE set PERSON.TWITTER_HANDLE = SOCIAL_PROFILE.TWITTER_HANDLE,
  PERSON.FACEBOOK_URL = SOCIAL_PROFILE.FACEBOOK_URL, PERSON.LINKEDIN_URL = SOCIAL_PROFILE.LINKEDIN_URL,
  PERSON.GOOGLE_PLUS_URL = SOCIAL_PROFILE.GOOGLE_PLUS_URL where PERSON.ID = SOCIAL_PROFILE.PERSON_ID;
drop table SOCIAL_PROFILE;
