# --- !Ups
create table FACILITATOR_LANGUAGE(
  PERSON_ID BIGINT NOT NULL,
  LANGUAGE CHAR(2) NOT NULL,
  PRIMARY KEY (PERSON_ID, LANGUAGE)
);

create table FACILITATOR_COUNTRY(
  PERSON_ID BIGINT NOT NULL,
  COUNTRY CHAR(2) NOT NULL,
  PRIMARY KEY (PERSON_ID, COUNTRY)
);
# --- !Downs
DROP TABLE FACILITATOR_LANGUAGE;
DROP TABLE FACILITATOR_COUNTRY;