# --- !Ups
ALTER TABLE ACCOUNT CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE BOOKING_ENTRY CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE BOOKING_ENTRY_ACTIVITY CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE CERTIFICATE_TEMPLATE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE CONTRIBUTION CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVALUATION CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVALUATION_IMPRESSION CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVENT_FACILITATOR CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVALUATION_QUESTION CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVALUATION_RECOMMENDATION CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVENT CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVENT_FACILITATOR CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVENT_INVOICE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVENT_PARTICIPANT CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE EVENT_TYPE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE FACILITATOR_COUNTRY CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE FACILITATOR_LANGUAGE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE PRODUCT CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE PRODUCT_BRAND_ASSOCIATION CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE SOCIAL_PROFILE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE TRANSACTION_TYPE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE EVENT MODIFY TITLE VARCHAR(254) CHARACTER SET utf8 NOT NULL;
ALTER TABLE EVENT MODIFY CITY VARCHAR(254) CHARACTER SET utf8 NOT NULL;
ALTER TABLE EVENT MODIFY DESCRIPTION TEXT CHARACTER SET utf8;
ALTER TABLE EVENT MODIFY SPECIAL_ATTENTION TEXT CHARACTER SET utf8;
ALTER TABLE EVENT MODIFY WEB_SITE VARCHAR(254) CHARACTER SET utf8;
ALTER TABLE EVENT MODIFY REGISTRATION_PAGE VARCHAR(254) CHARACTER SET utf8;

ALTER TABLE SOCIAL_PROFILE MODIFY TWITTER_HANDLE VARCHAR(254) CHARACTER SET utf8;
ALTER TABLE SOCIAL_PROFILE MODIFY FACEBOOK_URL VARCHAR(254) CHARACTER SET utf8;
ALTER TABLE SOCIAL_PROFILE MODIFY LINKEDIN_URL VARCHAR(254) CHARACTER SET utf8;
ALTER TABLE SOCIAL_PROFILE MODIFY GOOGLE_PLUS_URL VARCHAR(254) CHARACTER SET utf8;
ALTER TABLE SOCIAL_PROFILE MODIFY TWITTER_HANDLE VARCHAR(254) CHARACTER SET utf8;

# --- !Downs