# --- !Ups
ALTER TABLE BOOKING_ENTRY_ACTIVITY CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE CERTIFICATE_TEMPLATE CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE EVENT_FACILITATOR CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE EXCHANGE_RATE CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE PERMANENT_SESSION CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE PRODUCT_BRAND_ASSOCIATION CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

# --- !Downs
