# --- !Ups
ALTER TABLE ACTIVITY ADD COLUMN SUBJECT_ID BIGINT NOT NULL DEFAULT 0 AFTER ID;
ALTER TABLE ACTIVITY ADD COLUMN OBJECT_TYPE CHAR(20) NOT NULL DEFAULT "" AFTER PREDICATE;
ALTER TABLE ACTIVITY ADD COLUMN OBJECT_ID BIGINT NOT NULL DEFAULT 0 AFTER OBJECT_TYPE;
ALTER TABLE ACTIVITY ADD COLUMN SUPPORTIVE_OBJECT_TYPE CHAR(20) AFTER OBJECT;
ALTER TABLE ACTIVITY ADD COLUMN SUPPORTIVE_OBJECT_ID BIGINT DEFAULT 0 AFTER SUPPORTIVE_OBJECT_TYPE;
ALTER TABLE ACTIVITY ADD COLUMN SUPPORTIVE_OBJECT VARCHAR(254) AFTER SUPPORTIVE_OBJECT_ID;
# --- !Downs
ALTER TABLE ACTIVITY DROP COLUMN SUBJECT_ID;
ALTER TABLE ACTIVITY DROP COLUMN OBJECT_TYPE;
ALTER TABLE ACTIVITY DROP COLUMN OBJECT_ID;
ALTER TABLE ACTIVITY DROP COLUMN SUPPORTIVE_OBJECT;
ALTER TABLE ACTIVITY DROP COLUMN SUPPORTIVE_OBJECT_ID;
ALTER TABLE ACTIVITY DROP COLUMN SUPPORTIVE_OBJECT_TYPE;
