# --- !Ups
ALTER TABLE MEMBER ADD COLUMN SUBSCRIPTION TINYINT(1) DEFAULT 1 AFTER FEE;
ALTER TABLE MEMBER ADD COLUMN ACTIVE TINYINT(1) DEFAULT 0;

# --- !Downs
ALTER TABLE MEMBER DROP COLUMN SUBSCRIPTION;
ALTER TABLE MEMBER DROP COLUMN ACTIVE;