# --- !Ups
alter table EVENT_PARTICIPANT add column CERTIFICATE varchar(254) default NULL after EVALUATION_ID;
alter table EVENT_PARTICIPANT add column ISSUED date default NULL after CERTIFICATE;
update EVENT_PARTICIPANT as p, EVALUATION set p.CERTIFICATE = EVALUATION.CERTIFICATE where EVALUATION_ID = EVALUATION.ID;
update EVENT_PARTICIPANT as p, EVALUATION set ISSUED = EVALUATION.HANDLED where EVALUATION_ID = EVALUATION.ID;
alter table EVALUATION drop column CERTIFICATE;

# --- !Downs
alter table EVALUATION add column CERTIFICATE varchar(254) default NULL after HANDLED;
update EVALUATION as e, EVENT_PARTICIPANT set e.CERTIFICATE = EVENT_PARTICIPANT.CERTIFICATE where e.ID = EVENT_PARTICIPANT.EVALUATION_ID;
alter table EVENT_PARTICIPANT drop column CERTIFICATE;
alter table EVENT_PARTICIPANT drop column ISSUED;
