# --- !Ups
create table if not exists PAYMENT_RECORD (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  REMOTE_ID VARCHAR(254) NOT NULL UNIQUE KEY,
  PAYER_ID BIGINT NOT NULL,
  OBJECT_ID BIGINT NOT NULL,
  PERSON TINYINT(1) NOT NULL,
  DESCRIPTION VARCHAR(254) NOT NULL,
  FEE_CURRENCY CHAR(3) NOT NULL,
  FEE DECIMAL(13,3) NOT NULL,
  CREATED DATETIME NOT NULL);
# --- !Downs
drop table PAYMENT_RECORD;