/*
 * Happy Melly Teller
 * Copyright (C) 2013 - 2014, Happy Melly http://www.happymelly.com
 *
 * This file is part of the Happy Melly Teller.
 *
 * Happy Melly Teller is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Happy Melly Teller is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Happy Melly Teller.  If not, see <http://www.gnu.org/licenses/>.
 *
 * If you have questions concerning this license or the applicable additional terms, you may contact
 * by email Sergey Kotlov, sergey.kotlov@happymelly.com or
 * in writing Happy Melly One, Handelsplein 37, Rotterdam, The Netherlands, 3071 PR
 */

package views

object Countries {

  /**
   * Returns country name by its code
   * @param code Country code
   */
  def name(code: String): String = all.find(_._1 == code) map { _._2 } getOrElse ""

  val all =
    List(("AF", "Afghanistan"),
      ("AL", "Albania"),
      ("DZ", "Algeria"),
      ("AS", "American Samoa"),
      ("AD", "Andorra"),
      ("AO", "Angola"),
      ("AI", "Anguilla"),
      ("AG", "Antigua and Barbuda"),
      ("AR", "Argentina"),
      ("AM", "Armenia"),
      ("AW", "Aruba"),
      ("AC", "Ascension Island"),
      ("AU", "Australia"),
      ("AT", "Austria"),
      ("AZ", "Azerbaijan"),
      ("BS", "Bahamas"),
      ("BH", "Bahrain"),
      ("BD", "Bangladesh"),
      ("BB", "Barbados"),
      ("BY", "Belarus"),
      ("BE", "Belgium"),
      ("BZ", "Belize"),
      ("BJ", "Benin"),
      ("BM", "Bermuda"),
      ("BT", "Bhutan"),
      ("BO", "Bolivia"),
      ("BQ", "Bonaire, Saint Eustatius, and Saba"),
      ("BA", "Bosnia and Herzegovina"),
      ("BW", "Botswana"),
      ("BV", "Bouvet Island"),
      ("BR", "Brazil"),
      ("VG", "British Virgin Islands"),
      ("BN", "Brunei"),
      ("BG", "Bulgaria"),
      ("BF", "Burkina Faso"),
      ("BI", "Burundi"),
      ("KH", "Cambodia"),
      ("CM", "Cameroon"),
      ("CA", "Canada"),
      ("IC", "Canary Islands"),
      ("CT", "Canton and Enderbury Islands"),
      ("CV", "Cape Verde"),
      ("KY", "Cayman Islands"),
      ("CF", "Central African Republic"),
      ("EA", "Ceuta and Melilla"),
      ("TD", "Chad"),
      ("CL", "Chile"),
      ("CN", "China"),
      ("CX", "Christmas Island"),
      ("CP", "Clipperton Island"),
      ("CC", "Cocos (Keeling) Islands"),
      ("CO", "Colombia"),
      ("KM", "Comoros"),
      ("CG", "Congo - Brazzaville"),
      ("CD", "Congo - Kinshasa"),
      ("CK", "Cook Islands"),
      ("CR", "Costa Rica"),
      ("HR", "Croatia"),
      ("CU", "Cuba"),
      ("CW", "Curaçao"),
      ("CY", "Cyprus"),
      ("CZ", "Czech Republic"),
      ("CI", "Côte d’Ivoire"),
      ("DK", "Denmark"),
      ("DG", "Diego Garcia"),
      ("DJ", "Djibouti"),
      ("DM", "Dominica"),
      ("DO", "Dominican Republic"),
      ("NQ", "Dronning Maud Land"),
      ("EC", "Ecuador"),
      ("EG", "Egypt"),
      ("SV", "El Salvador"),
      ("GQ", "Equatorial Guinea"),
      ("ER", "Eritrea"),
      ("EE", "Estonia"),
      ("ET", "Ethiopia"),
      ("FK", "Falkland Islands"),
      ("FO", "Faroe Islands"),
      ("FJ", "Fiji"),
      ("FI", "Finland"),
      ("FR", "France"),
      ("GF", "French Guiana"),
      ("PF", "French Polynesia"),
      ("GA", "Gabon"),
      ("GM", "Gambia"),
      ("GE", "Georgia"),
      ("DE", "Germany"),
      ("GH", "Ghana"),
      ("GI", "Gibraltar"),
      ("GR", "Greece"),
      ("GL", "Greenland"),
      ("GD", "Grenada"),
      ("GP", "Guadeloupe"),
      ("GU", "Guam"),
      ("GT", "Guatemala"),
      ("GG", "Guernsey"),
      ("GN", "Guinea"),
      ("GW", "Guinea-Bissau"),
      ("GY", "Guyana"),
      ("HT", "Haiti"),
      ("HN", "Honduras"),
      ("HK", "Hong Kong"),
      ("HU", "Hungary"),
      ("IS", "Iceland"),
      ("IN", "India"),
      ("ID", "Indonesia"),
      ("IR", "Iran"),
      ("IQ", "Iraq"),
      ("IE", "Ireland"),
      ("IL", "Israel"),
      ("IT", "Italy"),
      ("JM", "Jamaica"),
      ("JP", "Japan"),
      ("JE", "Jersey"),
      ("JT", "Johnston Island"),
      ("JO", "Jordan"),
      ("KZ", "Kazakhstan"),
      ("KE", "Kenya"),
      ("KI", "Kiribati"),
      ("KW", "Kuwait"),
      ("KG", "Kyrgyzstan"),
      ("LA", "Laos"),
      ("LV", "Latvia"),
      ("LB", "Lebanon"),
      ("LS", "Lesotho"),
      ("LR", "Liberia"),
      ("LY", "Libya"),
      ("LI", "Liechtenstein"),
      ("LT", "Lithuania"),
      ("LU", "Luxembourg"),
      ("MO", "Macau"),
      ("MK", "Macedonia"),
      ("MG", "Madagascar"),
      ("MW", "Malawi"),
      ("MY", "Malaysia"),
      ("MV", "Maldives"),
      ("ML", "Mali"),
      ("MT", "Malta"),
      ("MH", "Marshall Islands"),
      ("MQ", "Martinique"),
      ("MR", "Mauritania"),
      ("MU", "Mauritius"),
      ("YT", "Mayotte"),
      ("MX", "Mexico"),
      ("FM", "Micronesia"),
      ("MI", "Midway Islands"),
      ("MD", "Moldova"),
      ("MC", "Monaco"),
      ("MN", "Mongolia"),
      ("ME", "Montenegro"),
      ("MS", "Montserrat"),
      ("MA", "Morocco"),
      ("MZ", "Mozambique"),
      ("MM", "Myanmar (Burma)"),
      ("NA", "Namibia"),
      ("NR", "Nauru"),
      ("NP", "Nepal"),
      ("NL", "Netherlands"),
      ("NC", "New Caledonia"),
      ("NZ", "New Zealand"),
      ("NI", "Nicaragua"),
      ("NE", "Niger"),
      ("NG", "Nigeria"),
      ("NU", "Niue"),
      ("NF", "Norfolk Island"),
      ("KP", "North Korea"),
      ("MP", "Northern Mariana Islands"),
      ("NO", "Norway"),
      ("OM", "Oman"),
      ("QO", "Outlying Oceania"),
      ("PK", "Pakistan"),
      ("PW", "Palau"),
      ("PS", "Palestinian Territories"),
      ("PA", "Panama"),
      ("PG", "Papua New Guinea"),
      ("PY", "Paraguay"),
      ("YD", "Democratic Republic of Yemen"),
      ("PE", "Peru"),
      ("PH", "Philippines"),
      ("PN", "Pitcairn Islands"),
      ("PL", "Poland"),
      ("PT", "Portugal"),
      ("PR", "Puerto Rico"),
      ("QA", "Qatar"),
      ("RO", "Romania"),
      ("RU", "Russia"),
      ("RW", "Rwanda"),
      ("RE", "Réunion"),
      ("BL", "Saint Barthélemy"),
      ("SH", "Saint Helena"),
      ("KN", "Saint Kitts and Nevis"),
      ("LC", "Saint Lucia"),
      ("MF", "Saint Martin"),
      ("PM", "Saint Pierre and Miquelon"),
      ("VC", "Saint Vincent and the Grenadines"),
      ("WS", "Samoa"),
      ("SM", "San Marino"),
      ("SA", "Saudi Arabia"),
      ("SN", "Senegal"),
      ("RS", "Serbia"),
      ("CS", "Serbia and Montenegro"),
      ("SC", "Seychelles"),
      ("SL", "Sierra Leone"),
      ("SG", "Singapore"),
      ("SX", "Sint Maarten"),
      ("SK", "Slovakia"),
      ("SI", "Slovenia"),
      ("SB", "Solomon Islands"),
      ("SO", "Somalia"),
      ("ZA", "South Africa"),
      ("KR", "South Korea"),
      ("ES", "Spain"),
      ("LK", "Sri Lanka"),
      ("SD", "Sudan"),
      ("SR", "Suriname"),
      ("SZ", "Swaziland"),
      ("SE", "Sweden"),
      ("CH", "Switzerland"),
      ("SY", "Syria"),
      ("ST", "São Tomé and Príncipe"),
      ("TW", "Taiwan"),
      ("TJ", "Tajikistan"),
      ("TZ", "Tanzania"),
      ("TH", "Thailand"),
      ("TL", "Timor-Leste"),
      ("TG", "Togo"),
      ("TK", "Tokelau"),
      ("TO", "Tonga"),
      ("TT", "Trinidad and Tobago"),
      ("TA", "Tristan da Cunha"),
      ("TN", "Tunisia"),
      ("TR", "Turkey"),
      ("TM", "Turkmenistan"),
      ("TC", "Turks and Caicos Islands"),
      ("TV", "Tuvalu"),
      ("UG", "Uganda"),
      ("UA", "Ukraine"),
      ("AE", "United Arab Emirates"),
      ("GB", "United Kingdom"),
      ("US", "United States"),
      ("ZZ", "Unknown Region"),
      ("UY", "Uruguay"),
      ("UZ", "Uzbekistan"),
      ("VU", "Vanuatu"),
      ("VE", "Venezuela"),
      ("VN", "Vietnam"),
      ("WK", "Wake Island"),
      ("WF", "Wallis and Futuna"),
      ("EH", "Western Sahara"),
      ("YE", "Yemen"),
      ("ZM", "Zambia"),
      ("ZW", "Zimbabwe"))

  val gdp = Map("QA" -> 1,
    "LU" -> 1,
    "MO" -> 1,
    "LI" -> 1,
    "SG" -> 1,
    "BN" -> 1,
    "KW" -> 1,
    "MC" -> 1,
    "BM" -> 1,
    "NO" -> 1,
    "SX" -> 1,
    "AE" -> 1,
    "CH" -> 1,
    "FK" -> 1,
    "JE" -> 1,
    "SN" -> 1,
    "HK" -> 1,
    "US" -> 2,
    "SA" -> 2,
    "NL" -> 2,
    "IE" -> 2,
    "BH" -> 2,
    "AT" -> 2,
    "AU" -> 2,
    "SE" -> 2,
    "DE" -> 2,
    "CA" -> 2,
    "DK" -> 2,
    "GG" -> 2,
    "OM" -> 2,
    "TW" -> 2,
    "IS" -> 2,
    "KY" -> 2,
    "BE" -> 2,
    "GI" -> 2,
    "FI" -> 2,
    "VG" -> 2,
    "FR" -> 2,
    "GB" -> 2,
    "JP" -> 3,
    "GL" -> 3,
    "NC" -> 3,
    "IT" -> 3,
    "NZ" -> 3,
    "AD" -> 3,
    "KR" -> 3,
    "ES" -> 3,
    "PM" -> 3,
    "GQ" -> 3,
    "IL" -> 3,
    "PR" -> 3,
    "MT" -> 3,
    "TT" -> 3,
    "AW" -> 3,
    "CZ" -> 3,
    "SI" -> 3,
    "CY" -> 3,
    "FO" -> 3,
    "GU" -> 3,
    "TC" -> 3,
    "SK" -> 3,
    "EE" -> 3,
    "LT" -> 3,
    "PT" -> 3,
    "GR" -> 3,
    "SC" -> 3,
    "PF" -> 3,
    "RU" -> 3,
    "BS" -> 3,
    "PL" -> 3,
    "MY" -> 3,
    "HU" -> 3,
    "KZ" -> 3,
    "LV" -> 3,
    "CL" -> 3,
    "AG" -> 3,
    "GA" -> 3,
    "HR" -> 3,
    "KN" -> 3,
    "UY" -> 3,
    "PA" -> 3,
    "RO" -> 3,
    "TR" -> 3,
    "BY" -> 4,
    "MU" -> 4,
    "MF" -> 4,
    "VE" -> 4,
    "LB" -> 4,
    "AZ" -> 4,
    "LY" -> 4,
    "MX" -> 4,
    "BG" -> 4,
    "SR" -> 4,
    "IR" -> 4,
    "AR" -> 4,
    "BB" -> 4,
    "BW" -> 4,
    "PW" -> 4,
    "BR" -> 4,
    "ME" -> 4,
    "CR" -> 4,
    "IQ" -> 4,
    "TH" -> 4,
    "CW" -> 4,
    "DZ" -> 4,
    "TM" -> 4,
    "CU" -> 4,
    "CO" -> 4,
    "RS" -> 4,
    "ZA" -> 4,
    "MP" -> 4,
    "MV" -> 4,
    "DO" -> 4,
    "CN" -> 4,
    "MK" -> 4,
    "AS" -> 4,
    "JO" -> 4,
    "PE" -> 4,
    "GD" -> 4,
    "TN" -> 4,
    "EC" -> 4,
    "LC" -> 4,
    "EG" -> 4,
    "AL" -> 4,
    "VC" -> 4,
    "DM" -> 4,
    "MN" -> 4,
    "NA" -> 4,
    "LK" -> 4,
    "ID" -> 4,
    "BA" -> 4,
    "JM" -> 4,
    "UA" -> 4,
    "PY" -> 4,
    "CK" -> 4,
    "BZ" -> 4,
    "MS" -> 4,
    "FJ" -> 4,
    "SV" -> 4,
    "AO" -> 4,
    "BT" -> 4,
    "SZ" -> 4,
    "GE" -> 4,
    "MA" -> 4,
    "GT" -> 4,
    "TA" -> 4,
    "AM" -> 4,
    "PH" -> 4,
    "GY" -> 4,
    "CV" -> 4,
    "CG" -> 4,
    "BO" -> 4,
    "NG" -> 4,
    "IN" -> 4,
    "WS" -> 4,
    "VN" -> 4)
}
